### PR TITLE
Rework of my original pr to port to python 3

### PR DESCRIPTION
**Pull request by Lunarequest**
This uses as much of the original code as possible without adding new dependencies.

### CODE REVIEW

**Comment by Lunarequest** [comment]
@marcan i reworked it since it had a lot of issues

**Comment by marcan** [comment]
Sorry for taking so long to look at this.

You still had a bunch of bytes/string issues, but it was easy to fix them so I just did it and force-pushed to your branch. Thanks!

**Comment by marcan** [comment]
Deployed to please.hackmii.com.

**Comment by Lunarequest** [comment]
thats awesome to here

**Pull request merged**
